name: casanova
description: Built by Neerd Developers

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  provider: ^4.3.2+2
  get_it: ^5.0.1
  cloud_firestore: ^0.14.0+2
  firebase_auth: ^0.18.0+1
  firebase_storage: ^4.0.0
  http: ^0.12.1
  url_launcher: ^5.5.0
  cached_network_image: ^2.3.1
  auto_size_text: ^2.1.0
  fluttertoast: ^7.0.1
  uuid: ^2.2.2
  share: ^0.6.4+5
  image: ^2.1.14
  path_provider: ^1.6.14
  shared_preferences: ^0.5.10
  image_picker: ^0.6.7+7
  location: ^3.0.2
  connectivity: ^0.4.9+2
  intl: ^0.16.1
  flushbar: ^1.10.4
  google_sign_in: ^4.5.3
  flutter_facebook_login: ^3.0.0
  smooth_star_rating: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
